services:
  - type: web
    name: ghost-blog
    env: docker
    plan: starter
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: TZ
        value: America/Sao_Paulo
    disk:
      - name: ghost-content
        mountPath: /var/lib/ghost/content
        sizeGB: 1
